# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Wordpress-Gears
tagline: Swag for WP Developers
github : wycks
twitter : wpsecurenet
production_url : http://wycks.github.com/WordPress-Gear/